name: flappwritechat
description: Flutter + Appwrite Chat Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^0.4.0-dev.1
  flutter_riverpod: ^0.13.0

dependency_overrides:
  appwrite:
    path: /home/dlohani/Documents/projects/appwrite/sdks/sdk-for-flutter
  web_socket_channel:
    path: /home/dlohani/Documents/projects/appwrite/sdks/web_socket_channel
    # git:
    #   url: https://github.com/lohanidamodar/web_socket_channel
    #   ref: feat-headers

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
