name: flappwritechat
description: Flutter + Appwrite Chat Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  appwrite: ^2.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.13.0
  responsive_builder: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
