name: flappwritechat
description: Flutter + Appwrite Chat Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^0.4.0-dev.1
  flutter_riverpod: ^0.13.0
  websok: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
